apiVersion: view.zoetrope.github.io/v1
kind: MarkdownView
metadata:
  labels:
    app.kubernetes.io/name: markdown-view
    app.kubernetes.io/managed-by: kustomize
  name: markdownview-sample
spec:
  markdowns:
    SUMMARY.md: |
      # Summary

      - [Page1](page1.md)
    page1.md: |
      # Page 1

      一ページ目のコンテンツです。
  replicas: 1
  viewerImage: "peaceiris/mdbook:latest"
