
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.1
  creationTimestamp: null
  name: markdownviews.viewer.zoetrope.github.io
spec:
  group: viewer.zoetrope.github.io
  names:
    kind: MarkdownView
    listKind: MarkdownViewList
    plural: markdownviews
    singular: markdownview
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.replicas
      name: REPLICAS
      type: integer
    - jsonPath: .status
      name: STATUS
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: MarkdownView is the Schema for the markdownviews API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MarkdownViewSpec defines the desired state of MarkdownView
            properties:
              markdowns:
                additionalProperties:
                  type: string
                description: Markdowns are
                type: object
              replicas:
                default: 1
                description: Replicas is the number of instances.
                format: int32
                type: integer
              viewerImage:
                description: ViewerImage is a image name
                type: string
            type: object
          status:
            description: MarkdownViewStatus defines the observed state of MarkdownView
            enum:
            - ready
            - available
            - healthy
            type: string
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
