apiVersion: multitenancy.example.com/v1
kind: Tenant
metadata:
  name: tenant-sample
spec:
  namespaces:
    - test1
    - test2
  admin:
    kind: ServiceAccount
    name: default
    namespace: default

